### ISSUE TITLE
tiny css change so placeholder text doesn't cut off

### ISSUE THREAD

**Issue by luckman212** [valentine195/obsidian-settings-search#12]
Thanks for this awesome plugin @valentine195 !

The placeholder text _"Search settings..."_ was being cut off on my system (I use the standard Dark theme)

I added this custom CSS to fix it:
```css
/* slightly wider settings nav area */
.modal.mod-settings .vertical-tab-header {
  flex: 0 0 220px;
}
```

Before the change:
<img width="214" alt="image" src="https://user-images.githubusercontent.com/1992842/157745015-7dda3482-c10f-4685-bb81-ce2ff5c4322b.png">

After this change:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/1992842/157744798-b2cefee7-0b93-4d34-b951-dc6d6f361174.png">
